### PR TITLE
fix: error modal in preview mode

### PR DESCRIPTION
**Pull request by caminoezequiel**

### CODE REVIEW

**Comment by menduz** [comment]
If we merge this, how do we visualize the errors in preview mode?

**Comment by caminoezequiel** [comment]
> If we merge this, how do we visualize the errors in preview mode?

@menduz We never had an error screens in the preview mode

**Comment by menduz** [comment]
I believe this PR exists because that `showErrorModal` function was called from the preview mode and it broke the user's scenes, otherwise we should not have this PR and we should close it, because that function should never be called

**Comment by menduz** [comment]
What I meant is that it happened, so we need to find a way to show the user errors on the preview, not silently fail.

**Review by menduz — CHANGES_REQUESTED** [review]
We should find a way to show the user errors in preview mode, not silently fail.

**Pull request closed without merging**
