### PR TITLE
chore: preload unity while signing

### PR DESCRIPTION
**Pull request by AjimenezDCL**
Fix decentraland/explorer#632

Currently we have a spinner blocking any signin interaction until unity is ready. The metrics show users dropping-off without even seeing the signin buttons due to large loading times. 

This PR addresses the situation by allowing the signin process to be started while the Unity build is loading in the background. The spinner now will be visible if after finishing signin Unity is not ready.

### CODE REVIEW

**Comment by AjimenezDCL** [comment]
After the CI passes:

- This branch can be previewed at https://play.decentraland.zone/branch/chore/preload_unity_while_signing/index.html?ENV=org
- The `decentraland-ecs` package can be tested in scenes by running
   ```bash
   npm install "https://play.decentraland.zone/branch/chore/preload_unity_while_signing/decentraland-ecs.tgz"
   ```

**Review by RominaMarchetti — COMMENTED** [review]
@AjimenezDCL it seems that the spinner was completely removed, and it's a problem considering that after clicking any button visual feedback is not shown anymore, making it look like the request isn't happening. 
In the landing both buttons disappear after clicking any of them while in the wallets modal nothing happens. In every case, we must show the spinner after clicking the buttons the same way it is happening now in prod if possible :)

**Comment by AjimenezDCL** [comment]
@RominaMarchetti 
> It seems that the spinner was completely removed, and it's a problem considering that after clicking any button visual feedback is not shown anymore, making it look like the request isn't happening.
> In the landing both buttons disappear after clicking any of them while in the wallets modal nothing happens. In every case, we must show the spinner after clicking the buttons the same way it is happening now in prod if possible :)

Ahhh I see what you mean, nice catch I overlook that spinner completly. Thanks!

**Review by RominaMarchetti — APPROVED** [review]

**Comment by AjimenezDCL** [comment]
Just found a bug. If you don't complete the signup process (leave in the middle of the avatar editor, for example) the next time you try to log-in the world loades with no profile.

**Review by D4rWiNSS — APPROVED** [review]
Tested in different situations, waiting, trying to enter as fast as possible, in incognito as guess and normal sign-in, it seems to work in all situations, Good job!

**Pull request merged**
