### PR TITLE
fix: preview mode enable web3 param

### PR DESCRIPTION
**Pull request by pravusjif**
**WHY**
after applying [this other PR](https://github.com/decentraland/explorer/pull/1933) the usage of the URL param `ENABLE_WEB3` for preview mode scenes got broken showing a `Could not get a wallet connection Error: Invalid provider Metamask` error.

**WHAT**
fixed old "metamask" authentication with new "injected" auth.

Thanks @pablitar for the awsome help.

### CODE REVIEW

**Review by nchamo — APPROVED** [review]
Great work!

Thanks for fixing this!

**Review by pbosio — COMMENTED** [review]
Is it OK to have a "log in" button in Preview Mode?
I suppose it's necessary for multiple wallets support, right?

**Comment by nchamo** [comment]
@pbosio 

Yeah, because when you enable web3, you need to log in exactly like in prod

**Comment by pravusjif** [comment]
> Is it OK to have a "log in" button in Preview Mode?

If you don't use the `ENABLE_WEB3` you are automatically logged in and don't see the buton at all =)

**Review by pbosio — APPROVED** [review]

**Pull request merged**
