### PR TITLE
feat: toast design integration

### PR DESCRIPTION
**Pull request by pravusjif**
* Designed and integrated new images for the different button actions (pointer, primary and secondary)

* Updated interaction hover to be fixed on screen space always instead of projected based on interactive object's mesh position

* Added missing canvas scaler to interaction hover canvas

---------------------------------------
One place with many interactive objects to test is around 52,-70 (ZONE)

### CODE REVIEW

**Review by pbosio — APPROVED** [review]

**Review by BrianAmadori — COMMENTED** [review]
The unknown interaction prefab is showing a left click icon, is this ok?
image

**Comment by RominaMarchetti** [comment]
@BrianAmadori icon updated.

**Comment by eordano** [comment]
where can I test this?

**Comment by RominaMarchetti** [comment]
@eordano 
> where can I test this?

How to test:
1. Open the "Assets/Scenes/Test/Misc/InteractiveObjectsHoverTest.unity" scene
2. hit PLAY and approach the Lantern model (you have to get close due to the interaction distance)

**Comment by pravusjif** [comment]
@eordano 
> where can I test this?

Actually you can just enter https://explorer.decentraland.zone/branch/feat/toast_design_integration/index.html?position=52,-70

At those coordinates there are several interactibles in zone

**Review by BrianAmadori — APPROVED** [review]
Its looking great :)

**Pull request merged**
