### PR TITLE
fix: avatar skewing

### PR DESCRIPTION
**Pull request by AjimenezDCL**
A side effect of using non-uniform scaling with parenting is the skewing of the childs. Adding a node with a  (1,1,1) scale between the non-uniform parent and the content should solve the issue.

EDIT: The above is invalid as a general solution. It will still fail in nested entities with arbitrary rotations/scales. The only way to solve this is by taking the CharacterRepresentation out of the parenting.

### CODE REVIEW

**Comment by pravusjif** [comment]
Where a re we rotating the character now? if we don't use its `transform.forward` anymore

**Comment by AjimenezDCL** [comment]
> Where a re we rotating the character now? if we don't use its `transform.forward` anymore

`rotationTransform.forward = characterForward.Get().Value; ` there

**Review by pravusjif — APPROVED** [review]

**Comment by BrianAmadori** [comment]
I don't see how adding an intermediate parent should fix the skewing, as the skewed scale is still carried over. How is this working @AjimenezDCL ?

**Comment by AjimenezDCL** [comment]
You are right, Brian. Is not a general solution. Gonna change the approach

**Comment by AjimenezDCL** [comment]
Already fixed

**Pull request closed without merging**
