### PR TITLE
fix: Awaiting user signature feedback & style fixes

### PR DESCRIPTION
**Pull request by pablitar**
# What? 
- Fixed some styles thanks to @RominaMarchetti 's feedback
- Added feedback for when the application is waiting the user's signature and it takes some time

image

### CODE REVIEW

**Comment by pravusjif** [comment]
test link https://play.decentraland.zone/fix/awaiting-user-signature-feedback/index.html?ENV=org

**Comment by pbosio** [comment]
> test link https://play.decentraland.zone/fix/awaiting-user-signature-feedback/index.html?ENV=org

https://play.decentraland.zone/branch/fix/awaiting-user-signature-feedback/index.html?ENV=org

**Review by pbosio — APPROVED** [review]

**Comment by pbosio** [comment]
Tested. Signature feedback appears correctly 👍

**Review by pravusjif — APPROVED** [review]
works fine!

**Pull request merged**
