### PR TITLE
fix: reduce acceleration

### PR DESCRIPTION
**Pull request by eordano**
# What? 
Drop the acceleration for the mouse

# Why? 
image

### CODE REVIEW

**Comment by BrianAmadori** [comment]
This is already being taken care of at https://github.com/decentraland/explorer/pull/1616. Please let's try to centralize the efforts here.

**Comment by eordano** [comment]
> This is already being taken care of at #1616. Please let's try to centralize the efforts here.

The purpose of this is to trigger a build so we can share different links with users testing different settings

**Comment by AjimenezDCL** [comment]
We could use this: https://play.decentraland.zone/branch/chore/1002_mouse_sensitivity_test/index.html for that

**Comment by eordano** [comment]
> We could use this: https://play.decentraland.zone/branch/chore/1002_mouse_sensitivity_test/index.html for that

Yes, this is useful to find good settings, but in order to do end-user testing we need actual links. Asking the user to use those sliders contaminates the tests.

**Pull request closed without merging**
