### PR TITLE
Feat: Use the new catalyst health check to verify a server is up before connecting

### PR DESCRIPTION
**Pull request by jmoguilevsky**
# What? 
Filters out non healthy catalyst peers, to prevent connecting to an unhealthy one

# Why? 
...

### CODE REVIEW

**Comment by menduz** [comment]
Are we waiting for all catalysts to whether succeed or fail? What happens if we have a gateway timeout of 50sec in _one_ of the catalysts? Will it hang for 50sec?

**Comment by jmoguilevsky** [comment]
do you think it would be better to do a promise race? 
The thing is that it needs to run the algorithm to choose a catalyst to compare between servers

**Comment by pablitar** [comment]
> do you think it would be better to do a promise race?
> The thing is that it needs to run the algorithm to choose a catalyst to compare between servers

We had this issue before when selecting which catalyst to connect to. We ended up using a timeout: https://github.com/decentraland/explorer/blob/master/kernel/packages/shared/dao/index.ts#L42

I'm not sure if we need to do that horrible stuff to have a timeout, but I'd see if we could have a timeout for this requests too. If a catalyst don't respond, at most you'd be blocked 5 or 10 seconds.

**Comment by jmoguilevsky** [comment]
Just added an abort controller to timeout at 5s, what do you think about that?
I think 5s is a good measure for a server that we don't want to connect to, either way, the score algorithm would've scored it very low

**Review by pablitar — APPROVED** [review]
LGTM!

**Pull request merged**
