### PR TITLE
fix: make watch

### PR DESCRIPTION
**Pull request by menduz**
# What? 
Fix make watch, some files were deleted

### CODE REVIEW

**Review by sandrade-dcl — APPROVED** [review]
It works! Thanks Agus.

**Comment by sandrade-dcl** [comment]
@menduz, can we merge it to `master`?

**Review by BrianAmadori — APPROVED** [review]

**Comment by BrianAmadori** [comment]
Merging this PR because we need it ASAP.

**Comment by menduz** [comment]
If the PR is not draft and it is approved, please consider it "mergeable" at any time

**Pull request merged**
