### PR TITLE
fix: metallic factor is applied with textures as well

### PR DESCRIPTION
**Pull request by AjimenezDCL**
#936 Metallic factor is now applied along a metallic texture as well. This will bring Unity's render closer to Babylon's sandbox

Before:
image

After:
image

### CODE REVIEW

**Comment by AjimenezDCL** [comment]
Remember to test thoroughly without Asset Bundles to find regressions

**Comment by menduz** [comment]
looking good

**Comment by pravusjif** [comment]
at this coordinates in ZONE we have a special test scene for material properties
https://play.decentraland.zone/branch/fix/936_metallic_factor_with_textures/index.html?ENV=zone&NO_ASSET_BUNDLES&position=58%2C-71

**Review by pravusjif — APPROVED** [review]
Didn't see anything strange, although maybe it would be wise to show this build to one of the Artists like Shibu to see if they catch something odd

**Review by BrianAmadori — APPROVED** [review]

**Review by ShibuyaMartin — APPROVED** [review]

**Pull request merged**
