### PR TITLE
feat: porting loading into unity

### PR DESCRIPTION
**Pull request by AjimenezDCL**
decentraland/unity-renderer#407

To test with this PR: https://github.com/decentraland/unity-renderer/pull/757

https://play.decentraland.zone/branch/feat/porting_loading_into_unity/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:feat/port_loading_into_unity

### CODE REVIEW

**Review by sandrade-dcl — APPROVED** [review]

**Review by kuruk-mm — APPROVED** [review]
Tested and it's working perfectly!

**Comment by menduz** [comment]
Screen Shot 2021-07-13 at 11 06 27

It hangs in that state, playing as guest, clearing local storage

**Review by menduz — CHANGES_REQUESTED** [review]
Screen Shot 2021-07-13 at 11 06 27

- It hangs in that state, playing as guest, clearing local storage. Second time works correctly. Reproductible every time.
- Between the avatar creation screen and the loading screen I still see an overlay with Decentraland logo. Is that intended to happen?

**Comment by AjimenezDCL** [comment]
@menduz not is not. Thanks for bringing it up, I couldn't reproduce it until I cleared the cache! gonna fix it.

**Comment by AjimenezDCL** [comment]
I believe every corner-case should be covered now. @menduz Do you mind taking another look? I haven't been able to reproduce any other weird behaviour.

**Review by menduz — APPROVED** [review]
Great job

**Pull request merged**
