### PR TITLE
feat: FPS counter toggle

### PR DESCRIPTION
**Pull request by eordano**

### CODE REVIEW

**Review by pravusjif — APPROVED** [review]

**Review by BrianAmadori — COMMENTED** [review]
Just entered at the test URL, typed /showfps, it showed the "Toggling FPS counter" message but no FPS can be seen. 
https://explorer.decentraland.zone/branch/feat/fps/index.html?position=-1%2C2

**Comment by eordano** [comment]
Hmm, weird. True, the renderer version shows a really old renderer... 
image

**Comment by moliva** [comment]
> Hmm, weird. True, the renderer version shows a really old renderer...
> image

Don't pay attention to that version, as it's taken from the module retrieved by NPM, but the *actual* build files are used. We just don't have tracking of it in these builds.

**Comment by eordano** [comment]
Now we're talking @BrianAmadori

**Review by BrianAmadori — APPROVED** [review]

**Pull request merged**
